# Site settings
title: Yohann's Blog
email: yuhang.ming@bristol.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Readings during my Ph.D. study.
baseurl: "/home" # the subpath of your site, e.g. /blog/
url: "http://yuhangming.github.io" # the base hostname & protocol for your site
twitter_username: username
github_username: username

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]