# Site settings
title: Yohann's Blog
description: I'm gonna write down things I learned along with my understandings.
url: "http://yuhangming.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author:
  name     : Yuhang Ming
  bio      : Ph.D. student in the Visual Information Lab in University of Bristol, currently working on semantic SLAM system.
  email    : yuhang.ming@bristol.ac.uk
  # twitter  : https://twitter.com/mateussousam

#SEO settings
logo: /assets/img/ym.jpg/ # Site logo URL
# twitter_username: mateussousam # Twitter username
# facebook:
#     app_id: 1445035275808959 # App ID
#     publisher: https://www.facebook.com/mateus.sousamedeiros # URL of the Facebook page
#     admins: 100000229048939 # Facebook user ID that manages the page

# Build settings
permalink: /:title/
markdown: kramdown
paginate: 5
paginate_path: "/blog/page/:num"

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

css_folder:  "/assets/css"
js_folder:  "/assets/js"
img_folder:  "/assets/img"
sass:
    style: compressed